### ISSUE TITLE
Cloning repos has strange theming

### ISSUE THREAD

**Issue by brian6932** [Ziyadsk/GithubDarkStyle#6]
Cloning repos inverts color on hover
![image](https://user-images.githubusercontent.com/18603393/87866108-7cb22000-c94b-11ea-9798-bcca6167c72e.png)

**Comment by Ziyadsk** [comment]
fixed in  https://github.com/Ziyadsk/GithubDarkStyle/commit/d1abbd32ed1569e4f59fae5378134b82dafcb483
