### ISSUE TITLE
Commits page has an unthemed listing/date bar

### ISSUE THREAD

**Issue by brian6932** [Ziyadsk/GithubDarkStyle#7]
Link: https://github.com/Ziyadsk/GithubDarkStyle/commits/master
Screenshot: ![image](https://user-images.githubusercontent.com/18603393/87866180-7e301800-c94c-11ea-863d-35426c68ed71.png)

**Comment by Ziyadsk** [comment]
Thanks again brian , fixed in https://github.com/Ziyadsk/GithubDarkStyle/commit/d1abbd32ed1569e4f59fae5378134b82dafcb483
